name: BendingScoreboard
main: com.AlexTheCoder.korra.scoreboard.BendingScoreboard
version: 0.1
authors: [jedk1]
depend: ['ProjectKorra']

commands:
  bboard:
    description: Default command for Bending Board!
    usage: /bboard
    aliases: bb
    permission: bboard.player
